### ISSUE TITLE
[Sponsor request] Logo on the sponsor page.

### ISSUE THREAD

**Issue by julians3** [wcasia/2025-website#1]
Notice there are only 3 tier listing on the sponsor page.

Kindly please assist to relayout of to show all 6 tiers with correct sizes, so the website team would work on it. thank you. 

SO SORRY got to chase you guys for it as we already have sponsors paid and we need to get the listing out fast.

https://www.figma.com/design/eZFoDyjdbHJAVgxsSugPz1/Website?node-id=2253-58381&node-type=canvas&t=CmGcubJTdMPii8Em-0

tag @gerlynnia77  @jrannelv

**Comment by gerlynnia77** [comment]
Hello @julians3 , I have updated the Sponsors Page Layout. You may check it here - https://www.figma.com/design/eZFoDyjdbHJAVgxsSugPz1/Website?node-id=2792-314028&t=cBRIXaWTyQvD0AIS-1

**Comment by julians3** [comment]
TQ @gerlynnia77 , is awesome!

Please passed to website team.
